### PR TITLE
fixed a deref of a null ptr

### PR DESCRIPTION
**Pull request by int-Frank**
Fixes [AB#1671](https://dev.azure.com/euclideon/57c3bd2a-8f94-4578-b195-2e4fa9d8f295/_workitems/edit/1671)

### CODE REVIEW

**Comment by samsinsane** [comment]
This overlaps with #676, we can probably close this and attach AB#1671 to that PR too?

**Comment by OsiJr** [comment]
@int-Frank, can you follow up on this PR?

**Comment by int-Frank** [comment]
@OsiJr @samsinsane Sam is correct. Although the geozone fallback is different in each of these. This PR we have:
                    current -> project
#676 we have
                    current -> preferred -> pProgramstate->geozone.
I'm not sure which one is correct in this context.

**Comment by OsiJr** [comment]
I'll close this, if its broken we can revisit. At the moment this doesn't merge and the attached issue is resolved.

**Pull request closed without merging**
