### PR TITLE
Hide map tiles when off

### PR DESCRIPTION
**Pull request by Jossos**
- Disabled Map tile selection when map tiles are turned off
- Fixes [AB#1936](https://dev.azure.com/euclideon/57c3bd2a-8f94-4578-b195-2e4fa9d8f295/_workitems/edit/1936)

### CODE REVIEW

**Comment by Jossos** [comment]
@samsinsane I've purposefully had the window not shrink from the removal of the tile icons. positioning is based on the window size

**Comment by samsinsane** [comment]
I can't imagine this being an acceptable solution to whoever reported this issue in the first place. It looks quite awful.

**Comment by Jossos** [comment]
what should it do then?

**Comment by samsinsane** [comment]
Resize and reposition?

**Review by samsinsane — APPROVED** [review]

**Pull request merged**
