### PR TITLE
Flythrough First Frame Constrain Max Time

### PR DESCRIPTION
**Pull request by Jossos**
- Fixed bug in calculating First frame max time
- Fixes [AB#2223](https://dev.azure.com/euclideon/57c3bd2a-8f94-4578-b195-2e4fa9d8f295/_workitems/edit/2223)

### CODE REVIEW

**Review by samsinsane — CHANGES_REQUESTED** [review]
I don't doubt that this fixes the reported issue, however, the start time of the first frame should always be 0.

**Review by peterAdams1014 — DISMISSED** [review]

**Comment by Jossos** [comment]
> I don't doubt that this fixes the reported issue, however, the start time of the first frame should always be 0.

I'm not sure if this is necessarily true. I'll discuss with Paul, but it's out of scope of this PR

**Comment by samsinsane** [comment]
The original code was setting the min and max of the first frame time to 0, this would indicate to me that the intention is for the first frame time to always be 0. How exactly is that out of scope for this PR?

**Comment by Jossos** [comment]
> The original code was setting the min and max of the first frame time to 0, this would indicate to me that the intention is for the first frame time to always be 0. How exactly is that out of scope for this PR?

so the min/max are for the drag scaler UI. The min is always the previous frames time, and the max is the next frames time. since 0th frame has no previous frame, it's just set to 0. This doesn't show any intention for the time of the first frame to always be 0, otherwise it would just set it to 0.

**Review by samsinsane — APPROVED** [review]

**Pull request merged**
